### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by hwnahm** [PassKit/passkit-node-quickstart#2]
% npm run test 

> passkit-node-quickstart@1.0.0 test
> jest

jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: std::__1::system_error: open: /Users/peter/Downloads/passkit-node-quickstart: Operation not permitted. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.
  console.log
    Creating images

      at QuickStartLoyalty.createImages (src/lib/quick-start-loyalty.js:105:13)

  console.log
    Error:  Error: 16 UNAUTHENTICATED: could not find a user record for user
        at Object.<anonymous>.exports.createStatusError (/Users/peter/Downloads/passkit-node-quickstart/node_modules/grpc/src/common.js:91:15)
        at Object.onReceiveStatus (/Users/peter/Downloads/passkit-node-quickstart/node_modules/grpc/src/client_interceptors.js:1209:28)
        at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (/Users/peter/Downloads/passkit-node-quickstart/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (/Users/peter/Downloads/passkit-node-quickstart/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/Users/peter/Downloads/passkit-node-quickstart/node_modules/grpc/src/client_interceptors.js:847:24) {
      code: 16,
      metadata: Metadata {
        _internal_repr: {
          date: [Array],
          'content-length': [Array],
          'strict-transport-security': [Array]
        },
        flags: 0
      },
      details: 'could not find a user record for user'
    }

      at QuickStartLoyalty.runQuickStart (src/lib/quick-start-loyalty.js:82:15)

  console.log
    Enrollment URL:  https://pub1.pskt.io/c/

      at Object.<anonymous> (src/test/quick-start-loyalty.test.js:49:13)

  console.log
    Bronze Pass Url:  https://pub1.pskt.io/

      at Object.<anonymous> (src/test/quick-start-loyalty.test.js:53:13)

  console.log
    Silver Pass Url:  https://pub1.pskt.io/

      at Object.<anonymous> (src/test/quick-start-loyalty.test.js:57:13)

  console.log
    Data will be removed in 1 minutes

      at Object.<anonymous> (src/test/quick-start-loyalty.test.js:62:13)

  console.log
    Delete Program

      at QuickStartLoyalty.deleteProgram (src/lib/quick-start-loyalty.js:425:13)

 FAIL  src/test/quick-start-loyalty.test.js (65.226 s)
  quick start loyalty
    ✕ has all image assets (1 ms)
    ✕ has template assets (2 ms)
    ✕ has program assets (1 ms)
    ✕ has tier assets
    ✕ has member assets (1 ms)
    ✓ has event assets
    ✓ shows urls (60005 ms)

  ● quick start loyalty › has all image assets

    TypeError: Cannot read properties of undefined (reading 'getIcon')

      14 | describe("quick start loyalty", () => {
      15 |   it("has all image assets", () => {
    > 16 |     expect(quickStart.imageIds.getIcon()).toBeTruthy();
         |                                ^
      17 |     expect(quickStart.imageIds.getLogo()).toBeTruthy();
      18 |     expect(quickStart.imageIds.getHero()).toBeTruthy();
      19 |     expect(quickStart.imageIds.getStrip()).toBeTruthy();

      at Object.<anonymous> (src/test/quick-start-loyalty.test.js:16:32)

  ● quick start loyalty › has template assets

    expect(received).toBeTruthy()

    Received: ""

      21 | 
      22 |   it("has template assets", () => {
    > 23 |     expect(quickStart.silverTemplateId).toBeTruthy();
         |                                         ^
      24 |     expect(quickStart.silverTemplateId).toBeTruthy();
      25 |     expect(quickStart.silverTemplateId.length).toBe(22);
      26 |     expect(quickStart.bronzeTemplateId.length).toBe(22);

      at Object.<anonymous> (src/test/quick-start-loyalty.test.js:23:41)

  ● quick start loyalty › has program assets

    expect(received).toBeTruthy()

    Received: ""

      28 | 
      29 |   it("has program assets", () => {
    > 30 |     expect(quickStart.programId).toBeTruthy();
         |                                  ^
      31 |     expect(quickStart.programId.length).toBe(22);
      32 |   });
      33 | 

      at Object.<anonymous> (src/test/quick-start-loyalty.test.js:30:34)

  ● quick start loyalty › has tier assets

    expect(received).toBeTruthy()

    Received: ""

      33 | 
      34 |   it("has tier assets", () => {
    > 35 |     expect(quickStart.silverTierId).toBeTruthy();
         |                                     ^
      36 |     expect(quickStart.bronzeTierId).toBeTruthy();
      37 |   });
      38 | 

      at Object.<anonymous> (src/test/quick-start-loyalty.test.js:35:37)

  ● quick start loyalty › has member assets

    expect(received).toBeTruthy()

    Received: ""

      38 | 
      39 |   it("has member assets", () => {
    > 40 |     expect(quickStart.bronzeMemberId).toBeTruthy();
         |                                       ^
      41 |     expect(quickStart.silverMemberId).toBeTruthy();
      42 |   });
      43 | 

      at Object.<anonymous> (src/test/quick-start-loyalty.test.js:40:39)

Test Suites: 1 failed, 1 total
Tests:       5 failed, 2 passed, 7 total
Snapshots:   0 total
Time:        65.463 s, estimated 66 s
Ran all test suites.
  console.log
    Error:  Error: 16 UNAUTHENTICATED: could not find a user record for user
        at Object.<anonymous>.exports.createStatusError (/Users/peter/Downloads/passkit-node-quickstart/node_modules/grpc/src/common.js:91:15)
        at Object.onReceiveStatus (/Users/peter/Downloads/passkit-node-quickstart/node_modules/grpc/src/client_interceptors.js:1209:28)
        at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (/Users/peter/Downloads/passkit-node-quickstart/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (/Users/peter/Downloads/passkit-node-quickstart/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/Users/peter/Downloads/passkit-node-quickstart/node_modules/grpc/src/client_interceptors.js:847:24) {
      code: 16,
      metadata: Metadata {
        _internal_repr: {
          date: [Array],
          'content-length': [Array],
          'strict-transport-security': [Array]
        },
        flags: 0
      },
      details: 'could not find a user record for user'
    }

      at QuickStartLoyalty.cleanUp (src/lib/quick-start-loyalty.js:99:15)

**Comment by canderson1538** [comment]
This has been resolved in the current quickstart. Unit tests no longer require Watchman, and credential-dependent tests are separated under npm run test:integration. Please ensure the .env credentials and PassKit region match your account when running integration tests.
