### ISSUE TITLE
FAIL  src/test/quick-start-loyalty.test.js

### ISSUE THREAD

**Issue by HarrisonHemstreet** [PassKit/passkit-node-quickstart#3]
Node version: 21.4.0
npm version: 10.4.0
OS: PopOS 22.04

I made sure to put the certs directory into the correct place along with all the .pem files. I also made sure to make necessary changes to the config file. I also made sure to double check my password was correct.

```bash
npm run test

> passkit-node-quickstart@1.0.0 test
> jest

 FAIL  src/test/quick-start-loyalty.test.js
  ● Test suite failed to run

    Failed to load gRPC binary module because it was not installed for the current system
    Expected directory: node-v120-linux-x64-glibc
    Found: [node-v67-linux-x64-glibc]
    This problem can often be fixed by running "npm rebuild" on the current system
    Original error: Cannot find module '/home/harry/alt-rew/passkit-node-quickstart/node_modules/grpc/src/node/extension_binary/node-v120-linux-x64-glibc/grpc_node.node' from 'node_modules/grpc/src/grpc_extension.js'

    Require stack:
      node_modules/grpc/src/grpc_extension.js
      node_modules/grpc/src/client_interceptors.js
      node_modules/grpc/src/client.js
      node_modules/grpc/index.js
      node_modules/passkit-node-sdk/io/core/a_rpc_templates_grpc_pb.js
      src/lib/client.js
      src/lib/quick-start-loyalty.js
      src/test/quick-start-loyalty.test.js


    However, Jest was able to find:
        './grpc_extension.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-arraystring

      1 | const {
      2 |   TemplatesClient,
    > 3 | } = require("passkit-node-sdk/io/core/a_rpc_templates_grpc_pb");
        |     ^
      4 | const {
      5 |   ImagesClient,
      6 | } = require("passkit-node-sdk/io/core/a_rpc_images_grpc_pb");

      at Object.<anonymous> (node_modules/grpc/src/grpc_extension.js:53:17)
      at Object.<anonymous> (node_modules/grpc/src/client_interceptors.js:144:12)
      at Object.<anonymous> (node_modules/grpc/src/client.js:35:27)
      at Object.<anonymous> (node_modules/grpc/index.js:27:14)
      at Object.<anonymous> (node_modules/passkit-node-sdk/io/core/a_rpc_templates_grpc_pb.js:4:12)
      at Object.<anonymous> (src/lib/client.js:3:5)
      at Object.<anonymous> (src/lib/quick-start-loyalty.js:28:21)
      at Object.<anonymous> (src/test/quick-start-loyalty.test.js:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.404 s
Ran all test suites.
(node:24668) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by JWLangford** [comment]
@HarrisonHemstreet an updated version of the node sdk and quickstart have been published. Can you try pulling the latest quickstart, deleting your node_modules, reinstalling, and re-running the tests?
